# Generated by Django 5.0.6 on 2024-05-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactus_email_pet_orderitem_order_breed_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='breed',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='breed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='email',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
