# Generated by Django 5.0.6 on 2024-05-16 19:59

import api.models.product
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_email_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='breed',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeds', to='api.pet'),
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=api.models.product.product_id, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/animal/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/animal/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/animal/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_approved', models.BooleanField(default=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.breed')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='animal',
            field=models.ForeignKey(default='Ea5i58', on_delete=django.db.models.deletion.PROTECT, to='api.animal'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
