# Generated by Django 5.0.6 on 2024-05-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_orderitem_product_alter_breed_pet_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='data',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_size',
        ),
    ]
