# Generated by Django 5.0.6 on 2024-05-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_animal_data_remove_animal_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='checked_out',
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order', to='api.orderitem'),
        ),
    ]
