# Generated by Django 5.0.6 on 2024-06-05 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_address_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.animal'),
        ),
    ]
