# Generated by Django 5.0.6 on 2024-06-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_orderitem_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='', upload_to='images/animal/'),
            preserve_default=False,
        ),
    ]
